### PR TITLE
Chips and Electric Components.

### PR DESCRIPTION
**Pull request by DarthSidiousPalpatine**
Slightly Updated old Sprites.

Electric Components 32x HUE
Misc Components

### CODE REVIEW

**Review by jrddunbr — CHANGES_REQUESTED** [review]
Some of these textures are not centered, can you make sure that they are all centered? Thanks!

**Comment by jrddunbr** [comment]
The `build` test doesn't run on PR's that come from outside of the organization. This is not important for this PR because it's not code.

**Comment by DarthSidiousPalpatine** [comment]
Everything is Centered now

**Review by jrddunbr — APPROVED** [review]
Nice.

**Pull request merged**
