### PR TITLE
Ktlintfix

### PR DESCRIPTION
**Pull request by Baughn**
Fixes most of the lints introduced by ktlint.

This forces us to use spaces, not tabs. Gah.

### CODE REVIEW

**Comment by jrddunbr** [comment]
GitHub dumped the entire rest of the output of this linter into my email. And then Gmail told me the mail was too large for my inbox and that I had to read the raw text.

Proposal:
* Disable 120 character limit
* Disable "Missing spacing before < and > and { and  } and :"
* Disable "Imports must be ordered in lexicographic order without any empty lines in-between"

You already know about the tabs issue.

**Comment by jrddunbr** [comment]
Perhaps changing from `info` to `warning` in the linter would also be a good idea. Not sure if that would catch documentation errors though (or if it does right now, which is honestly most of what it does anyways)

**Comment by Baughn** [comment]
The idea is, I believe, that the linter should only catch lint errors introduced by any given PR.

This one touches *everything*, so it falsely thinks it introduces all the errors, but future PRs won't keep showing the same lint messages.

**Comment by jrddunbr** [comment]
Ahhh, that makes sense.

**Comment by jrddunbr** [comment]
Here goes nothing!

**Pull request merged**
